baseURL = "https://dafydd.dev"
title = "Dafydd Henke - Accessibility Fool"
paginate = 5
theme = "PaperMod"
enableInlineShortcodes = true
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
enableEmoji = true

[minify]
disableXML = true

[outputs]
home = [ "HTML", "RSS", "JSON" ]

[params]
env = "production"
description = "Dafydd Henke - Personal Website"
author = "Dafydd Henke"
defaultTheme = "auto"
ShowReadingTime = true

[params.homeInfoParams]
  Title = "Dafydd Henke"
  Content = "Head of Accessibility at [AbilityNet](https://www.abilitynet.org.uk)."
