baseURL = "https://dafydd.dev"
title = "Dafydd Henke-Reed"
paginate = 5
theme = "PaperMod"
enableInlineShortcodes = true
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
enableEmoji = true

[minify]
disableXML = true

[outputs]
home = [ "HTML", "RSS", "JSON" ]

[params]
env = "production"
description = "Dafydd Henke-Reed Personal Website"
author = "Dafydd Henke-Reed"
defaultTheme = "auto"
ShowShareButtons = true
ShowReadingTime = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true

[params.homeInfoParams]
  Title = "PaperMod"
  Content = "Blah"

[[params.socialIcons]]
name = "github"
url = "https://github.com/adityatelange/hugo-PaperMod"

[[params.socialIcons]]
name = "twitter"
url = "https://github.com/adityatelange/hugo-PaperMod"
