baseURL = "https://dafydd.dev"
title = "Dafydd Henke - Accessibility Fool"
paginate = 5
theme = "PaperMod"
enableInlineShortcodes = true
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
enableEmoji = true
disableScrollToTop = false

[minify]
disableXML = true

[outputs]
home = [ "HTML", "RSS", "JSON" ]

[params]
env = "production"
description = "Dafydd Henke - Personal Website"
author = "Dafydd Henke"
defaultTheme = "auto"
ShowReadingTime = true
keywords = ["blog", "portfolio", "accessibility", "a11y", "web development"]

[params.homeInfoParams]
Title = "Dafydd Henke"
Content = '''
Hello, I am Dafydd. It is Welsh for David 🏴󠁧󠁢󠁷󠁬󠁳󠁿.\
\
I help make digital things more accessible. I am the Head of Accessibility at [AbilityNet](https://www.abilitynet.org.uk).
Say hello, if you like. My email is dafyddhenke AT gmail DOT com.
'''

[[menu.main]]
identifier = "Talks"
name = "Talks"
url = "/talks/"
weight = 10

[[menu.main]]
identifier = "Archive"
name = "Archive"
url = "/archives/"
weight = 20
