baseURL = "https://dafydd.dev"
title = "Dafydd Henke - Accessibility Fool"
paginate = 5
theme = "PaperMod"
enableInlineShortcodes = true
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
enableEmoji = true

[minify]
disableXML = true

[outputs]
home = [ "HTML", "RSS", "JSON" ]

[params]
env = "production"
description = "Dafydd Henke - Personal Website"
author = "Dafydd Henke"
defaultTheme = "auto"
ShowReadingTime = true

[params.homeInfoParams]
  Title = "Dafydd Henke"
  Content = '''
  Hello, I help make all things digital more accessible.\
  I'm the Head of Accessibility at [AbilityNet](https://www.abilitynet.org.uk).\
  Say hello, if you like. My email is dafyddhenke AT gmail DOT com.\
  (psst, Dafydd is Welsh for David 🏴󠁧󠁢󠁷󠁬󠁳󠁿)
  '''

[[menu.main]]
identifier = "Archive"
name = "Archive"
url = "/archives/"
weight = 10
