baseURL = "https://effortless-pudding-7ddf9d.netlify.app"
title = "David - Web Dev Fool"
paginate = 5
theme = "PaperMod"
enableInlineShortcodes = true
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
enableEmoji = true
disableScrollToTop = false

[minify]
disableXML = true

[outputs]
home = [ "HTML", "RSS", "JSON" ]

[params]
env = "production"
description = "David - Portfolio Website"
author = "David"
defaultTheme = "auto"
ShowReadingTime = true
keywords = ["blog", "portfolio", "accessibility", "a11y", "web development"]

[params.homeInfoParams]
Title = "David Portfolio"
Content = '''
## Introductions
Hello, I am David. I'm from Wales. Welcome to my portfolio 🏴󠁧󠁢󠁷󠁬󠁳󠁿.\
\
I help make develop websites and apps. I am the [job title] at [ACME Corp](https://www.example.com).
Say hello, if you like. My email is example AT gmail DOT com.\
\
Let me know what you think of my website!
[my smiling at camera](https://www.bristol.ac.uk/media-library/sites/tel/images/AbilityNet_Dafydd-283x380.png)
'''

[[menu.main]]
identifier = "Articles"
name = "Articles"
url = "/posts/"
weight = 20

[[menu.main]]
identifier = "Search"
name = "Search"
url = "/Search/"
weight = 30